#version 430 core

layout (local_size_x = 32, local_size_y = 32) in;

layout(rgba32f, binding = 0) uniform image2D outputImg;

layout(binding = 0) uniform sampler2D GBuffer0;
layout(binding = 1) uniform sampler2D GBuffer1;
layout(binding = 2) uniform sampler2D GBuffer2;
layout(binding = 3) uniform sampler2D GBuffer3;
layout(binding = 4) uniform sampler2D DepthTex;
layout(binding = 5) uniform samplerBuffer lightTex;



